### ISSUE TITLE
debug error on run

### ISSUE THREAD

**Issue by alexeinz** [unparagoned/njsTuya#30]
Hi, I am getting  error running the script njstuya.js
the actual node node_modules/njstuya  works fine....
any suggestions?

> root@lasermini:/opt/openhab/conf/scripts/node_modules# node njstuya.js 
> internal/modules/cjs/loader.js:638
>     throw err;
>     ^
> 
> Error: Cannot find module '/opt/openhab/conf/scripts/node_modules/njstuya.js'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
>     at startup (internal/bootstrap/node.js:283:19)
>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by unparagoned** [comment]
You run ```node node_modules njstuya``` or ```node node_modules/njstuya/njstuya.js```
