### ISSUE TITLE
Error: Timeout waiting for response

### ISSUE THREAD

**Issue by thib5** [unparagoned/njsTuya#7]
Hi,

When I test your thing with the command line and test :  node njstuya.js -ip 192.168.X.X -id 062007as2qedsdsc2e7d888 -key 881da7sdasdasdas4fd5a State I get :

>  resolveIds() is deprecated since v3.0.0. Will be removed in v4.0.0. Use resolveId() instead. 

and then I receive the State. 

When  I try : node njstuya.js -ip 192.168.X.X -id 062007as2qedsdsc2e7d888 -key 881da7sdasdasdas4fd5a ON or OFF I get : 

> resolveIds() is deprecated since v3.0.0. Will be removed in v4.0.0. Use resolveId() instead.
> Error: Timeout waiting for response

And nothing happen ...

**Comment by burroz** [comment]
Same for me,... STATE returns the actual state but all others time out,... Any ideas?

**Comment by unparagoned** [comment]
You should just be able to ignore the warning. It will work fine otherwise. You problem is elsewhere. Status should be quite gentle since the key can be wrong. Make sure the your id and ip are correct. 


If you don't want a warning install an earlier version of tuyapi say 2.0.3

**Comment by unparagoned** [comment]
> Same for me,... STATE returns the actual state but all others time out,... Any ideas?

@burroz Your key is probably wrong. The status function doesn't rely on the key but the other function do.

**Comment by burroz** [comment]
> @burroz Your key is probably wrong. The status function doesn't rely on the key but the other function do.

You're right, I had some difficulties finding the keys - using https://github.com/TuyaAPI/cli helped me. Now using the correct keys the console command works as expected.

Thanks
