### ISSUE TITLE
error copying files - bad names

### ISSUE THREAD

**Issue by thebitpit** [unparagoned/njsTuya#9]

**Comment by thebitpit** [comment]
In the Readme

Then copy the files to Openhab configuration directories:

cp node_modules/njstuya/scripts/* $openhab/scripts
cp nodemodules/njstuya/items/* $openhab/items/
cp nodemodules/njstuya/rules/* $openhab/rules/

The second and third file names are are wrong.  "nodemodules" should be "node_modules"

**Comment by unparagoned** [comment]
Thanks. Fixed
